config/routes.rb
Rails.application.routes.draw do
  resources :messages
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'

  get 'welcome/mail' => 'welcome#mail'

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  #before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  respond_to :html, :js
  

  before_filter :cors_preflight_check
  after_filter :cors_set_access_control_headers
  #For all responses in this controller, return the CORS access control headers.
  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = 'http://localhost:9292'
    headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS'
    headers['Access-Control-Request-Method'] = 'http://localhost:9292'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
  end
  # If this is a preflight OPTIONS request, then short-circuit the
  # request, return only the necessary headers and return an empty
  # text/plain.
  def cors_preflight_check
    if request.method == :options
      headers['Access-Control-Allow-Origin'] = 'http://localhost:9292'
      headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS'
      headers['Access-Control-Request-Method'] = 'http://localhost:9292'
      headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
      render :text => '', :content_type => 'text/plain'
    end
  end


  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
    @new_message = current_user.messages.build
  end

  # GET /messages/1 
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = current_user.messages.build(message_params)
    #@message = Message.new(message_params)

    respond_to do |format|
      if @message.save

        ConfirmacionMailer.confirmacion_email(current_user).deliver_now

        sync_new @message
        #format.html { redirect_to @message, notice: 'Message was successfully created.' }
        #format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:body, :user_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  end

  def mail

  	@user = User.find( current_user.id );

  	respond_to do |format|
      # Sends email to user when user is created.
      #ExampleMailer.sample_email(@user).deliver / deliver_later  / deliver_now
      
      ConfirmacionMailer.confirmacion_email(@user).deliver_now
		#SendEmailJob.set(wait: 20.seconds).perform_later(@user)

		format.html
      #format.html { redirect_to @user, notice: 'User was successfully created.' }
      #format.json { render :show, status: :created, location: @user }
	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= include_sync_config %>
</head>
<body>
<!--
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
-->
<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Messages</h1>

<%= sync partial: 'messages', collection: @messages %>
<%= sync_new partial: 'messages', resource: Message.new %>

<br>

<%= form_for @new_message, remote: true do |f| %>
    <%= f.text_field :body %>
<% end %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @message.user.email %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/sync/messages/_messages.html.erb
<b><%= message.user.email %>: </b>
<td><%= message.body %></td>
</br>

app/views/welcome/index.html.erb
<h1>Hola Ruby</h1>
<p>pagina inicial</p>

<%= link_to 'Mensajes', controller: 'messages' %>
<br>
<a href="welcome/mail">Envio de email</a>